name: fao-shap-dashboard
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.37.0
      - pandas==2.2.2
      - numpy==1.26.4
      - scikit-learn==1.5.1
      - shap==0.45.1
      - matplotlib==3.8.4
      - plotly==5.22.0
      - jupyterlab==4.2.5
      - jupyter-server-proxy==4.4.0
